# Generated by Django 2.0.4 on 2018-05-13 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(choices=[('BASF', 'BASF AG, Germany'), ('Danisco', 'Danisco A/S, Denmark'), ('Firmenich', 'Firmenich SA, Switzerland'), ('Giv.', 'Givaudan SA, Switzerland'), ('IFF', 'International Flavors & Fragrances, USA'), ('Quest', 'Quest International, UK'), ('Symrise', 'Symrise GmbH & Co KG, Germany'), ('Takasago', 'Takasago Perfumery Co., Japan'), ('Vioryl', 'Vioryl SA, Greece')], default='', max_length=25)),
                ('structure', models.CharField(choices=[('ali', 'Aliphatic'), ('atp', 'Acyclic terpence'), ('ctp', 'Cyclic terpene'), ('ocy', 'Other cycloaliphatic'), ('aro', 'Aromatic'), ('het', 'Heterocyclic')], max_length=2)),
                ('fg_subdivision', models.CharField(choices=[('hyd', 'Hydrocarbon'), ('alc', 'Alcohol or ether'), ('ald', 'Aldehyde or acetal'), ('ket', 'Ketone'), ('cad', 'Carboxylic acid derivative'), ('cye', 'Cyclic ether'), ('lac', 'Lactone'), ('msc', 'Miscellaneous')], max_length=3)),
                ('cas_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('\\d+(?:-\\d+)+', 'String should be a valid CAS number')], verbose_name='CAS number')),
                ('smiles', models.CharField(default='', editable=False, max_length=100, verbose_name='SMILES string')),
                ('iupac_name', models.CharField(default='', editable=False, max_length=100, verbose_name='IUPAC name')),
            ],
            options={
                'ordering': ['structure'],
            },
        ),
        migrations.CreateModel(
            name='Odor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='compound',
            name='odor',
            field=models.ManyToManyField(related_name='compounds', to='compounds.Odor'),
        ),
    ]
