# Generated by Django 2.0.4 on 2018-05-19 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, choices=[('-----', ''), ('BASF', 'BASF AG, Germany'), ('Danisco', 'Danisco A/S, Denmark'), ('Firmenich', 'Firmenich SA, Switzerland'), ('Giv.', 'Givaudan SA, Switzerland'), ('IFF', 'International Flavors & Fragrances, USA'), ('Quest', 'Quest International, UK'), ('Symrise', 'Symrise GmbH & Co KG, Germany'), ('Takasago', 'Takasago Perfumery Co., Japan'), ('Vioryl', 'Vioryl SA, Greece')], default='', max_length=25)),
                ('trade_name', models.CharField(blank=True, default='', max_length=20, verbose_name='Trade name')),
                ('cas_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('\\d+(?:-\\d+)+', 'String should be a valid CAS number')], verbose_name='CAS number')),
                ('smiles', models.CharField(default='', editable=False, max_length=100, verbose_name='SMILES string')),
                ('iupac_name', models.CharField(default='', editable=False, max_length=200, verbose_name='IUPAC name')),
                ('cid_number', models.IntegerField(blank=True, editable=False, null=True, verbose_name='PubChem API CID number')),
            ],
            options={
                'ordering': ['-trade_name', 'iupac_name'],
            },
        ),
        migrations.CreateModel(
            name='Odor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='compound',
            name='odor',
            field=models.ManyToManyField(related_name='compounds', to='compounds.Odor'),
        ),
    ]
