# Generated by Django 2.0.4 on 2018-07-14 18:52

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Odorant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='SMILES string')),
                ('iupac_name', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=500, verbose_name='IUPAC name')),
                ('cid_number', models.IntegerField(blank=True, verbose_name='PubChem API CID number')),
                ('chemical_properties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False)),
                ('trade_name', models.CharField(blank=True, default='', max_length=20, verbose_name='Trade name')),
                ('cas_number', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('\\d+(?:-\\d+)+', 'String should be a valid CAS number')], verbose_name='CAS number')),
                ('odor_description', models.CharField(blank=True, default='', max_length=500, verbose_name='Odor description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OdorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Substructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='SMILES string')),
                ('iupac_name', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=500, verbose_name='IUPAC name')),
                ('cid_number', models.IntegerField(blank=True, verbose_name='PubChem API CID number')),
                ('name', models.CharField(help_text='Empirical name e.g. tetrahydrolinalools', max_length=50, verbose_name='Substructure class name')),
                ('description', models.CharField(blank=True, default='', max_length=340)),
                ('slug', models.SlugField(blank=True, default='')),
                ('iupac_name_pattern', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, default=list, size=None)),
                ('odor_categories', models.ManyToManyField(blank=True, related_name='Substructures', to='compounds.OdorType', verbose_name='Odor categories')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(max_length=500)),
                ('compound', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_set', to='compounds.Odorant')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_set', to='compounds.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='odorant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odorant', to='compounds.Profile'),
        ),
        migrations.AddField(
            model_name='odorant',
            name='odor_categories',
            field=models.ManyToManyField(blank=True, related_name='odorants', to='compounds.OdorType', verbose_name='Odor categories'),
        ),
    ]
