# Generated by Django 2.0.4 on 2018-05-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='trade_name',
            field=models.CharField(default='', max_length=20, verbose_name='Trade name'),
        ),
    ]
