# Generated by Django 2.0.4 on 2018-05-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='odor_description',
            field=models.CharField(default='', max_length=500, verbose_name='Odor description'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='odor',
            field=models.ManyToManyField(related_name='compounds', to='compounds.Odor', verbose_name='Odor Category'),
        ),
    ]
