# Generated by Django 2.0.4 on 2018-05-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='iupac_name',
            field=models.CharField(default='', editable=False, max_length=200, verbose_name='IUPAC name'),
        ),
    ]
