# Generated by Django 2.0.4 on 2018-05-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0002_auto_20180515_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='fg_subdivision',
            field=models.CharField(blank=True, choices=[('hyd', 'Hydrocarbon'), ('alc', 'Alcohol or ether'), ('ald', 'Aldehyde or acetal'), ('ket', 'Ketone'), ('cad', 'Carboxylic acid derivative'), ('cye', 'Cyclic ether'), ('lac', 'Lactone'), ('msc', 'Miscellaneous')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='structure',
            field=models.CharField(blank=True, choices=[('ali', 'Aliphatic'), ('atp', 'Acyclic terpence'), ('ctp', 'Cyclic terpene'), ('ocy', 'Other cycloaliphatic'), ('aro', 'Aromatic'), ('het', 'Heterocyclic')], max_length=2, null=True),
        ),
    ]
