# Generated by Django 2.0.4 on 2018-05-20 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0002_auto_20180520_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compound',
            options={},
        ),
        migrations.AlterField(
            model_name='compound',
            name='cas_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('\\d+(?:-\\d+)+', 'String should be a valid CAS number')], verbose_name='CAS number'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='supplier',
            field=models.CharField(blank=True, choices=[('BASF', 'BASF AG, Germany'), ('Danisco', 'Danisco A/S, Denmark'), ('Firmenich', 'Firmenich SA, Switzerland'), ('Giv.', 'Givaudan SA, Switzerland'), ('IFF', 'International Flavors & Fragrances, USA'), ('Quest', 'Quest International, UK'), ('Symrise', 'Symrise GmbH & Co KG, Germany'), ('Takasago', 'Takasago Perfumery Co., Japan'), ('Vioryl', 'Vioryl SA, Greece')], default='', max_length=25),
        ),
    ]
