# Generated by Django 2.0.4 on 2018-05-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0003_auto_20180520_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Odor',
            new_name='OdorType',
        ),
        migrations.AlterField(
            model_name='compound',
            name='odor_description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Odor description'),
        ),
    ]
