# Generated by Django 2.0.4 on 2018-07-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0004_auto_20180717_0000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserNotes',
            new_name='UserCompound',
        ),
    ]
