# Generated by Django 2.0.4 on 2018-05-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0004_auto_20180524_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compound',
            old_name='odor',
            new_name='odor_category',
        ),
    ]
