# Generated by Django 2.0.4 on 2018-05-26 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0005_auto_20180525_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='additional_cas',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator('\\d+(?:-\\d+)+', 'String should be a valid CAS number')], verbose_name='Additional registered CAS numbers'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='odor_category',
            field=models.ManyToManyField(related_name='compounds', to='compounds.OdorType', verbose_name='Odor categories'),
        ),
    ]
