# Generated by Django 2.0.4 on 2018-07-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0005_auto_20180717_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('webpage', models.URLField(max_length=500)),
                ('price_info', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usercompound',
            name='sources',
            field=models.ManyToManyField(blank=True, null=True, to='compounds.UserSource', verbose_name='User compounds sources'),
        ),
    ]
