# Generated by Django 2.0.4 on 2018-07-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0006_auto_20180719_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompound',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='usersource',
            name='name',
        ),
        migrations.AddField(
            model_name='usersource',
            name='compound',
            field=models.ManyToManyField(blank=True, related_name='sources', to='compounds.UserCompound', verbose_name='User compounds sources'),
        ),
        migrations.AddField(
            model_name='usersource',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
