# Generated by Django 2.0.4 on 2018-06-02 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0006_auto_20180526_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='odor_category',
        ),
        migrations.AddField(
            model_name='compound',
            name='odor_categories',
            field=models.ManyToManyField(related_name='compounds', to='compounds.OdorType', verbose_name='Odor categories'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='additional_cas',
            field=models.CharField(blank=True, default='', max_length=200, validators=[django.core.validators.RegexValidator('\\d+(?:-\\d+)+', 'String should be a valid CAS number')], verbose_name='Additional registered CAS numbers'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='cid_number',
            field=models.IntegerField(default=1234, editable=False, verbose_name='PubChem API CID number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compound',
            name='iupac_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='IUPAC name'),
        ),
    ]
