# Generated by Django 2.0.4 on 2018-07-20 14:21

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0007_auto_20180719_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bioactive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='SMILES string')),
                ('iupac_name', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=500, verbose_name='IUPAC name')),
                ('cid_number', models.IntegerField(blank=True, verbose_name='PubChem API CID number')),
                ('chemical_properties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False)),
                ('trade_name', models.CharField(blank=True, default='', max_length=20, verbose_name='Trade name')),
                ('category', models.IntegerField(choices=[(1, 'Medicinal compound'), (2, 'Functional food ingredient'), (3, 'Phytochemical'), (4, 'Miscellaneous')])),
                ('inchikey', models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]+(-[A-Z]+)*$', 'String must be a valid InChIKey')], verbose_name='InChIKey identifier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bioactives', to='compounds.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
