# Generated by Django 2.0.4 on 2018-06-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0008_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
