# Generated by Django 2.0.4 on 2018-07-20 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0009_auto_20180720_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usersource',
            name='price_info',
        ),
        migrations.RemoveField(
            model_name='usersource',
            name='webpage',
        ),
        migrations.AddField(
            model_name='usersource',
            name='amount',
            field=models.FloatField(default=1, help_text='Product amount in kg', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersource',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound'), ('EUR', 'Euro'), ('IND', 'Indian Rupee')], default='USD', help_text='Currency code', max_length=3, validators=[django.core.validators.RegexValidator('\\d+(?:-\\d+)+', 'Format must be e.g. USD')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersource',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersource',
            name='product_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usersource',
            name='specification',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usersource',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usersource',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usersource',
            name='compound',
            field=models.ManyToManyField(related_name='sources', to='compounds.UserCompound', verbose_name='User compounds sources'),
        ),
    ]
