# Generated by Django 2.0.4 on 2018-06-07 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0009_auto_20180606_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=25, unique=True)),
                ('latin_name', models.CharField(blank=True, default='', max_length=50)),
                ('edible', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='compound',
            name='occurrence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compounds', to='compounds.Occurrence', verbose_name='Characteristic natural occurrence'),
        ),
    ]
