# Generated by Django 2.0.4 on 2018-06-12 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compounds', '0010_auto_20180607_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compounds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compound',
            name='cid_number',
            field=models.IntegerField(blank=True, editable=False, verbose_name='PubChem API CID number'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compounds', to='compounds.Occurrence', verbose_name='Characteristic natural occurrence'),
        ),
    ]
