# Generated by Django 2.0.4 on 2018-06-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0011_auto_20180612_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(default='', max_length=100, verbose_name='SMILES string')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Substructure class name')),
                ('image', models.FileField(blank=True, upload_to='substructures/')),
                ('description', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
