# Generated by Django 2.0.4 on 2018-07-21 09:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0011_auto_20180721_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOdorantSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollars'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound'), ('EUR', 'Euro'), ('IND', 'Indian Rupee')], help_text='Currency code', max_length=3, validators=[django.core.validators.RegexValidator('\\d+(?:-\\d+)+', 'Format must be e.g. USD')])),
                ('amount', models.FloatField(help_text='Product amount in kg', max_length=20)),
                ('specification', models.CharField(blank=True, default='', max_length=100)),
                ('supplier', models.CharField(blank=True, default='', max_length=50)),
                ('product_number', models.CharField(blank=True, default='', max_length=20)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='usersource',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='userodorant',
            name='odorant',
        ),
        migrations.AddField(
            model_name='userodorant',
            name='compound',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='compounds.Odorant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userodorant',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.Profile'),
        ),
        migrations.DeleteModel(
            name='UserSource',
        ),
        migrations.AddField(
            model_name='userodorantsource',
            name='compound',
            field=models.ManyToManyField(related_name='sources', to='compounds.UserOdorant', verbose_name='User odorant compound sources'),
        ),
    ]
