# Generated by Django 2.0.4 on 2018-07-21 10:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0012_auto_20180721_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='userodorantsource',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='compounds.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userodorantsource',
            name='compound',
            field=models.ManyToManyField(related_name='odorant_sources', to='compounds.UserOdorant', verbose_name='User odorant compound sources'),
        ),
        migrations.AlterField(
            model_name='userodorantsource',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound'), ('EUR', 'Euro'), ('IND', 'Indian Rupee')], help_text='Currency code', max_length=3, validators=[django.core.validators.RegexValidator('(?<![A-Z])[A-Z]{3}(?![A-Z])', 'Format must be e.g. USD')]),
        ),
    ]
