# Generated by Django 2.0.4 on 2018-06-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0013_auto_20180617_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='occurrence',
        ),
        migrations.AlterField(
            model_name='substructure',
            name='cid_number',
            field=models.IntegerField(blank=True, verbose_name='PubChem API CID number'),
        ),
        migrations.DeleteModel(
            name='Occurrence',
        ),
    ]
