# Generated by Django 2.0.4 on 2018-07-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0013_auto_20180721_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userodorantsource',
            name='specification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userodorantsource',
            name='supplier',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
