# Generated by Django 2.0.4 on 2018-07-22 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0015_auto_20180721_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userodorantsource',
            name='compound',
        ),
        migrations.AddField(
            model_name='userodorantsource',
            name='compound',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='compounds.UserOdorant'),
            preserve_default=False,
        ),
    ]
