# Generated by Django 2.0.4 on 2018-06-17 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0015_compoundnotes_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundnotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='compounds.Profile'),
        ),
    ]
