# Generated by Django 2.0.4 on 2018-07-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0016_auto_20180722_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userodorantsource',
            old_name='compound',
            new_name='user_compound',
        ),
        migrations.RemoveField(
            model_name='userodorantsource',
            name='user',
        ),
    ]
