# Generated by Django 2.0.4 on 2018-07-22 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0017_auto_20180722_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userodorantsource',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollars'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound'), ('EUR', 'Euro'), ('IND', 'Indian Rupee')], default='', max_length=3, validators=[django.core.validators.RegexValidator('(?<![A-Z])[A-Z]{3}(?![A-Z])', 'Format must be e.g. USD')]),
        ),
    ]
