# Generated by Django 2.0.4 on 2018-07-24 18:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0018_auto_20180722_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompoundSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(blank=True, choices=[('', ''), ('USD', 'US Dollars'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound'), ('EUR', 'Euro'), ('IND', 'Indian Rupee')], default='', max_length=3, validators=[django.core.validators.RegexValidator('(?<![A-Z])[A-Z]{3}(?![A-Z])', 'Format must be e.g. USD')])),
                ('amount', models.FloatField(help_text='Product amount in kg', max_length=20)),
                ('specification', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=50)),
                ('product_number', models.CharField(blank=True, default='', max_length=20)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('user_odorant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.UserOdorant')),
            ],
        ),
        migrations.RemoveField(
            model_name='userodorantsource',
            name='user_compound',
        ),
        migrations.AlterField(
            model_name='bioactive',
            name='category',
            field=models.IntegerField(choices=[(1, 'Medicinal compound'), (2, 'Functional food ingredient'), (3, 'Miscellaneous')]),
        ),
        migrations.DeleteModel(
            name='UserOdorantSource',
        ),
    ]
