# Generated by Django 2.0.4 on 2018-07-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0019_auto_20180724_2046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCompoundSource',
            new_name='CompoundSource',
        ),
    ]
