# Generated by Django 2.0.4 on 2018-07-24 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0021_userbioactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundsource',
            name='user_bioactive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.UserBioactive'),
        ),
        migrations.AlterField(
            model_name='compoundsource',
            name='user_odorant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.UserOdorant'),
        ),
    ]
