# Generated by Django 2.0.4 on 2018-06-29 22:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0021_auto_20180626_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='substructure',
            name='iupac_name_pattern',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='compound',
            name='odor_categories',
            field=models.ManyToManyField(blank=True, related_name='compounds', to='compounds.OdorType', verbose_name='Odor categories'),
        ),
    ]
