# Generated by Django 2.0.4 on 2018-07-27 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0022_auto_20180724_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bioactive',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='odorant',
            name='created_by',
        ),
    ]
