# Generated by Django 2.0.4 on 2018-06-29 22:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0022_auto_20180630_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substructure',
            name='iupac_name_pattern',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, default=list, size=None),
        ),
    ]
