# Generated by Django 2.0.4 on 2018-06-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0023_auto_20180630_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='substructure',
            name='iupac_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='IUPAC name'),
        ),
    ]
