# Generated by Django 2.0.4 on 2018-07-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0023_auto_20180728_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='odorant',
            name='chemical_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Chemical name'),
        ),
    ]
