# Generated by Django 2.0.4 on 2018-06-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0024_substructure_iupac_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='substructure',
            name='odor_categories',
            field=models.ManyToManyField(blank=True, related_name='Substructures', to='compounds.OdorType', verbose_name='Odor categories'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='smiles',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='SMILES string'),
        ),
        migrations.AlterField(
            model_name='substructure',
            name='name',
            field=models.CharField(help_text='Empirical name e.g. tetrahydrolinalools', max_length=50, verbose_name='Substructure class name'),
        ),
        migrations.AlterField(
            model_name='substructure',
            name='smiles',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='SMILES string'),
        ),
    ]
