# Generated by Django 2.0.4 on 2018-07-27 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0024_odorant_chemical_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odorant',
            name='trade_name',
        ),
    ]
