# Generated by Django 2.0.4 on 2018-07-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0025_auto_20180630_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compounds.Profile'),
        ),
    ]
