# Generated by Django 2.0.4 on 2018-07-29 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0025_remove_odorant_trade_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='odorant',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compounds.Profile'),
        ),
        migrations.AlterField(
            model_name='bioactive',
            name='chemical_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Chemical name'),
        ),
        migrations.AlterField(
            model_name='odorant',
            name='chemical_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Chemical name'),
        ),
        migrations.AlterField(
            model_name='substructure',
            name='name',
            field=models.CharField(help_text='Uncapitalized Empirical name e.g. tetrahydrolinalools', max_length=50, verbose_name='Substructure class name'),
        ),
    ]
