# Generated by Django 2.0.4 on 2018-07-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0026_auto_20180729_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='substructure',
            name='category',
            field=models.IntegerField(choices=[(1, 'Terpene alcohol'), (2, '')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bioactive',
            name='category',
            field=models.IntegerField(choices=[(1, 'Medicinal compound'), (2, 'Functional food compound'), (3, 'Miscellaneous')]),
        ),
        migrations.AlterField(
            model_name='substructure',
            name='name',
            field=models.CharField(help_text='Empirical name e.g. tetrahydrolinalools', max_length=50, verbose_name='Substructure class name'),
        ),
    ]
