# Generated by Django 2.0.4 on 2018-07-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0026_compound_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='updated_by',
        ),
    ]
