# Generated by Django 2.0.4 on 2018-07-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0027_remove_compound_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substructure',
            name='description',
            field=models.CharField(blank=True, default='', max_length=340),
        ),
    ]
