# Generated by Django 2.0.4 on 2018-07-31 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0027_auto_20180729_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substructure',
            name='odor_categories',
        ),
        migrations.AddField(
            model_name='substructure',
            name='odor_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substructures', to='compounds.OdorType', verbose_name='Odor categories'),
        ),
        migrations.AlterField(
            model_name='substructure',
            name='category',
            field=models.IntegerField(choices=[(1, 'Acyclic terpenoids'), (2, 'Cyclic terpenoids'), (3, 'Bicyclic terpenoids'), (4, 'Sesquiterpenoids'), (5, 'Damascones, Ionones and Jasmones'), (6, 'Miscellaneous')]),
        ),
    ]
