# Generated by Django 2.0.4 on 2018-07-08 13:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0028_auto_20180707_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='chemical_properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
