# Generated by Django 2.0.4 on 2018-07-31 22:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0028_auto_20180731_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioactive',
            name='category',
            field=models.IntegerField(choices=[(1, 'Medicinal compound'), (2, 'Phytochemical'), (3, 'Miscellaneous')]),
        ),
        migrations.AlterField(
            model_name='substructure',
            name='category',
            field=models.IntegerField(choices=[(1, 'Acyclic terpenoids'), (2, 'Cyclic terpenoids'), (3, 'Bicyclic terpenoids'), (4, 'Sesquiterpenoids'), (5, 'Damascones and Ionones'), (6, 'Miscellaneous')]),
        ),
        migrations.AlterField(
            model_name='substructure',
            name='iupac_name_pattern',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=None),
        ),
    ]
