# Generated by Django 2.0.4 on 2018-08-02 20:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0029_auto_20180801_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioactiveCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='SMILES string')),
                ('iupac_name', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=500, verbose_name='IUPAC name')),
                ('cid_number', models.IntegerField(blank=True, verbose_name='PubChem API CID number')),
                ('slug', models.SlugField(blank=True, default='')),
                ('iupac_name_pattern', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
