# Generated by Django 2.0.4 on 2018-08-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0030_bioactivecore'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioactivecore',
            name='category',
            field=models.IntegerField(choices=[(1, 'Medicinal compound'), (2, 'Phytochemical'), (3, 'Miscellaneous')], default=2),
            preserve_default=False,
        ),
    ]
