# Generated by Django 2.0.4 on 2018-08-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0031_bioactivecore_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioactivecore',
            name='name',
            field=models.CharField(default='isothiocyanates', help_text='Empirical name e.g. isothiocyanates', max_length=50, verbose_name='Substructure class name'),
            preserve_default=False,
        ),
    ]
