# Generated by Django 2.0.4 on 2018-08-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0032_bioactivecore_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bioactivecore',
            name='iupac_name_pattern',
        ),
        migrations.AlterField(
            model_name='bioactivecore',
            name='name',
            field=models.CharField(help_text='Empirical name e.g. Isothiocyanates', max_length=50, verbose_name='Substructure class name'),
        ),
    ]
