# Generated by Django 2.0.4 on 2018-08-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0033_auto_20180803_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioactivecore',
            name='related_smiles',
            field=models.CharField(blank=True, db_index=True, default='', help_text='For substructure matches of close analogues', max_length=100, verbose_name='Related SMILES string'),
        ),
    ]
