# Generated by Django 2.0.4 on 2018-08-04 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0035_auto_20180804_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AT', 'Alimentary tract and metabolism'), ('AN', 'Antineoplastic and immunomodulating agents'), ('AP', 'Antiparasitics'), ('BM', 'Blood modifiers'), ('CV', 'Cardiovascular system'), ('DM', 'Dermatologicals'), ('GU', 'Genito-urinary system and sex hormones'), ('MS', 'Musculo-skeletal system'), ('NS', 'Nervous system'), ('RS', 'Respiratory system'), ('SA', 'Systemic antiinfectives'), ('SH', 'Systemic hormones'), ('VR', 'Various')], max_length=2)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bioactive',
            name='classification',
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
        migrations.AddField(
            model_name='bioactive',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bioactives', to='compounds.Activity', verbose_name='Primary pharmacological classification'),
        ),
    ]
