# Generated by Django 2.0.4 on 2018-08-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0036_auto_20180804_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='classification',
            field=models.CharField(blank=True, choices=[('AT', 'Alimentary tract and metabolism'), ('AN', 'Antineoplastic and immunomodulating agents'), ('AP', 'Antiparasitics'), ('BM', 'Blood modifiers'), ('CV', 'Cardiovascular system'), ('DM', 'Dermatologicals'), ('GU', 'Genito-urinary system and sex hormones'), ('MS', 'Musculo-skeletal system'), ('NS', 'Nervous system'), ('RS', 'Respiratory system'), ('SA', 'Systemic antiinfectives'), ('SH', 'Systemic hormones'), ('VR', 'Various')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'action'), (2, 'mechanism')]),
        ),
    ]
