# Generated by Django 2.0.4 on 2018-08-05 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0037_auto_20180805_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compounds.Activity'),
        ),
    ]
