# Generated by Django 2.0.4 on 2018-08-05 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0038_activity_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mechanisms', to='compounds.Activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=28, unique=True),
        ),
        migrations.AlterField(
            model_name='bioactive',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bioactives', to='compounds.Activity', verbose_name='Pharmacological activity'),
        ),
    ]
