# Generated by Django 2.0.4 on 2018-08-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0039_auto_20180805_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioactive',
            name='cid_number_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anionic form CID number'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'parent/action'), (2, 'child/mechanism')], db_index=True),
        ),
        migrations.AlterField(
            model_name='bioactive',
            name='category',
            field=models.IntegerField(choices=[(1, 'Pharmaceutical'), (2, 'Phytochemical'), (3, 'Miscellaneous')]),
        ),
        migrations.AlterField(
            model_name='bioactivecore',
            name='category',
            field=models.IntegerField(choices=[(1, 'Pharmaceutical'), (2, 'Phytochemical'), (3, 'Miscellaneous')]),
        ),
    ]
