# Generated by Django 2.0.4 on 2018-08-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0040_auto_20180807_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.IntegerField(choices=[(1, 'Action'), (2, 'Mechanism')], db_index=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='classification',
            field=models.CharField(choices=[('AT', 'Alimentary tract and metabolism'), ('AN', 'Antineoplastic and immunomodulating agents'), ('AP', 'Antiparasitics'), ('BM', 'Blood modifiers'), ('CV', 'Cardiovascular system'), ('DM', 'Dermatologicals'), ('GU', 'Genito-urinary system and sex hormones'), ('MS', 'Musculo-skeletal system'), ('NS', 'Nervous system'), ('RS', 'Respiratory system'), ('SA', 'Systemic antiinfectives'), ('SH', 'Systemic hormones'), ('VR', 'Various')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
