# Generated by Django 2.0.4 on 2018-08-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0041_auto_20180807_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='classification',
            field=models.CharField(choices=[('AT', 'Alimentary tract and metabolism'), ('AI', 'Antiinfectives'), ('AN', 'Antineoplastic and immunomodulating agents'), ('AP', 'Antiparasitics'), ('CV', 'Cardiovascular system'), ('DM', 'Dermatologicals'), ('GU', 'Genito-urinary system and sex hormones'), ('MS', 'Musculo-skeletal system'), ('NS', 'Nervous system'), ('RS', 'Respiratory system'), ('SH', 'Systemic hormones'), ('VR', 'Various')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='bioactive',
            name='chemical_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Chemical name'),
        ),
        migrations.AlterField(
            model_name='bioactive',
            name='iupac_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=500, verbose_name='IUPAC name'),
        ),
        migrations.AlterField(
            model_name='bioactive',
            name='smiles',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='SMILES string'),
        ),
        migrations.AlterField(
            model_name='odorant',
            name='chemical_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Chemical name'),
        ),
        migrations.AlterField(
            model_name='odorant',
            name='iupac_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=500, verbose_name='IUPAC name'),
        ),
        migrations.AlterField(
            model_name='odorant',
            name='smiles',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='SMILES string'),
        ),
    ]
