# Generated by Django 2.0.4 on 2018-08-13 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0042_auto_20180808_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundsource',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'grams'), ('kg', 'kilograms')], default='g', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='bioactive_set',
            field=models.ManyToManyField(blank=True, through='compounds.UserBioactive', to='compounds.Bioactive', verbose_name='Bioactive compound set'),
        ),
        migrations.AddField(
            model_name='profile',
            name='odorant_set',
            field=models.ManyToManyField(blank=True, through='compounds.UserOdorant', to='compounds.Odorant', verbose_name='Bioactive compound set'),
        ),
        migrations.AlterField(
            model_name='bioactive',
            name='category',
            field=models.IntegerField(choices=[(1, 'Pharmaceutical'), (2, 'food')]),
        ),
        migrations.AlterField(
            model_name='bioactivecore',
            name='category',
            field=models.IntegerField(choices=[(1, 'Pharmaceutical'), (2, 'food')]),
        ),
        migrations.AlterField(
            model_name='compoundsource',
            name='amount',
            field=models.FloatField(help_text='Product amount in <django.db.models.fields.CharField>', max_length=20),
        ),
        migrations.AlterField(
            model_name='compoundsource',
            name='user_bioactive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbioactive_sources', to='compounds.UserBioactive'),
        ),
        migrations.AlterField(
            model_name='compoundsource',
            name='user_odorant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userodorant_sources', to='compounds.UserOdorant'),
        ),
        migrations.AlterField(
            model_name='odorant',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_compounds', to='compounds.Profile'),
        ),
    ]
