# Generated by Django 2.0.4 on 2018-08-15 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0044_auto_20180815_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundsource',
            name='bioactive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bioactive_sources', to='compounds.Bioactive'),
        ),
        migrations.AddField(
            model_name='compoundsource',
            name='odorant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odorant_sources', to='compounds.Odorant'),
        ),
        migrations.AlterField(
            model_name='compoundsource',
            name='specification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='compoundsource',
            name='url',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
    ]
