# Generated by Django 2.0.4 on 2018-08-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0045_auto_20180815_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundsource',
            name='amount',
            field=models.FloatField(max_length=6),
        ),
        migrations.AlterField(
            model_name='compoundsource',
            name='specification',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='compoundsource',
            name='supplier',
            field=models.CharField(max_length=25),
        ),
    ]
