# Generated by Django 2.0.4 on 2018-08-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0048_auto_20180819_0129'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbioactive',
            unique_together={('compound', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userodorant',
            unique_together={('compound', 'user')},
        ),
    ]
