# Generated by Django 2.0.4 on 2018-08-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0049_auto_20180819_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbioactive',
            name='notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userodorant',
            name='notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
