# Generated by Django 2.0.4 on 2018-09-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0050_auto_20180826_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioactive',
            name='category',
            field=models.IntegerField(choices=[(1, 'Pharmaceutical'), (2, 'Nutraceutical')]),
        ),
        migrations.AlterField(
            model_name='bioactive',
            name='chemical_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Chemical name'),
        ),
        migrations.AlterField(
            model_name='bioactive',
            name='iupac_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=300, verbose_name='IUPAC name'),
        ),
        migrations.AlterField(
            model_name='bioactivecore',
            name='category',
            field=models.IntegerField(choices=[(1, 'Pharmaceutical'), (2, 'Nutraceutical')]),
        ),
        migrations.AlterField(
            model_name='odorant',
            name='chemical_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Chemical name'),
        ),
        migrations.AlterField(
            model_name='odorant',
            name='iupac_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=300, verbose_name='IUPAC name'),
        ),
    ]
