# Generated by Django 2.0.4 on 2018-09-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0051_auto_20180904_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('classification', 'name')},
        ),
    ]
