# Generated by Django 2.0.4 on 2018-09-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0052_auto_20180905_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='classification',
            field=models.CharField(choices=[('AT', 'Alimentary tract and metabolism'), ('AI', 'Antiinfectives'), ('AN', 'Anticancer agents'), ('AP', 'Antiparasitics'), ('CV', 'Cardiovascular system'), ('DM', 'Dermatologicals'), ('GU', 'Genito-urinary and sex hormones'), ('MS', 'Musculo-skeletal system'), ('NS', 'Nervous system'), ('RS', 'Respiratory system')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='bioactivecore',
            name='name',
            field=models.CharField(db_index=True, help_text='Empirical name e.g. Isothiocyanates', max_length=50, verbose_name='Substructure class name'),
        ),
    ]
