# Generated by Django 2.0.4 on 2018-09-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0053_auto_20180918_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioactivecore',
            name='bioactives',
            field=models.ManyToManyField(blank=True, related_name='substructures', to='compounds.Bioactive', verbose_name='Core derivatives'),
        ),
    ]
