# Generated by Django 2.0.4 on 2018-09-22 23:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0054_bioactivecore_bioactives'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
