# Generated by Django 2.0.4 on 2018-09-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0055_activity_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioactive',
            name='approval_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
