# Generated by Django 2.0.4 on 2018-10-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0057_auto_20181026_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioactive',
            name='hit_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
