# Generated by Django 2.0.4 on 2018-10-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0058_bioactive_hit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='odorant',
            name='hit_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
