# Generated by Django 2.0.4 on 2018-11-04 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0060_auto_20181103_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enzyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Galactosidase')], db_index=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('pdb_number', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('[\\w]{4}', 'String should be a valid PDB number')], verbose_name='PDP number')),
            ],
        ),
    ]
