# Generated by Django 2.0.4 on 2018-11-04 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0061_enzyme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enzyme',
            name='pdb_number',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('[\\w]{4}', 'String should be a valid PDB number')], verbose_name='PDB number'),
        ),
    ]
