# Generated by Django 2.0.4 on 2018-11-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0062_auto_20181104_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='enzyme',
            name='long_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='enzyme',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
