# Generated by Django 2.0.4 on 2018-11-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0063_auto_20181104_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enzyme',
            name='long_name',
        ),
        migrations.RemoveField(
            model_name='enzyme',
            name='name',
        ),
        migrations.AddField(
            model_name='enzyme',
            name='source',
            field=models.CharField(default=1, max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
