# Generated by Django 2.0.4 on 2018-11-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0064_auto_20181104_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='enzyme',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='enzyme',
            name='source',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
