# Generated by Django 2.0.4 on 2018-11-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0065_auto_20181104_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='enzyme',
            name='citation',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
