# Generated by Django 2.0.4 on 2018-11-07 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0066_enzyme_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='enzyme',
            name='mechanisms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enzymes', to='compounds.Activity'),
        ),
    ]
