# Generated by Django 2.0.4 on 2018-11-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0068_auto_20181107_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
