# Generated by Django 2.0.4 on 2018-11-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0070_auto_20181111_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bioactive',
            name='hit_count',
        ),
        migrations.RemoveField(
            model_name='odorant',
            name='hit_count',
        ),
        migrations.AlterField(
            model_name='activity',
            name='classification',
            field=models.CharField(blank=True, choices=[('AT', 'Alimentary tract and metabolism'), ('AI', 'Antiinfectives'), ('AN', 'Anticancer agents'), ('CV', 'Cardiovascular system'), ('GU', 'Genito-urinary and sex hormones'), ('MI', 'Miscellaneous'), ('MS', 'Musculo-skeletal system'), ('NS', 'Nervous system'), ('RS', 'Respiratory system')], db_index=True, max_length=2, null=True),
        ),
    ]
