# Generated by Django 2.0.4 on 2018-11-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0072_auto_20181119_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substructure',
            name='max_carbons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
