# Generated by Django 2.0.4 on 2018-11-29 23:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0073_auto_20181119_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('info_url', models.URLField(max_length=100, unique=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField(choices=[(0, 'Abandoned'), (1, 'Phase 1'), (2, 'Phase 2'), (3, 'Phase 3')])),
                ('clinic_info', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=2), blank=True, default=list, help_text='Links to clinical trials', size=None)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bioactives', to='compounds.CompanyPipeline')),
            ],
        ),
        migrations.AlterField(
            model_name='substructure',
            name='category',
            field=models.IntegerField(choices=[(1, 'Acyclic terpenoids'), (2, 'Cyclic terpenoids'), (3, 'Aromatic Compounds'), (5, 'Cycloaliphatics')]),
        ),
        migrations.AddField(
            model_name='bioactive',
            name='development',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.Development'),
        ),
    ]
