# Generated by Django 2.0.4 on 2018-11-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0074_auto_20181129_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='development',
            name='clinic_info',
        ),
        migrations.AddField(
            model_name='development',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Current trial completion date'),
        ),
        migrations.AddField(
            model_name='development',
            name='trial_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
