# Generated by Django 2.0.4 on 2018-11-30 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0075_auto_20181129_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bioactive',
            name='development',
        ),
        migrations.AddField(
            model_name='development',
            name='development',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='development', to='compounds.Bioactive'),
        ),
    ]
