# Generated by Django 2.0.4 on 2018-11-30 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0076_auto_20181130_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='development',
            name='development',
        ),
        migrations.AddField(
            model_name='development',
            name='bioactive',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='development', to='compounds.Bioactive'),
        ),
    ]
