# Generated by Django 2.0.4 on 2018-11-30 20:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0077_auto_20181130_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='lit_refs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=None, verbose_name='Literature References'),
        ),
    ]
