# Generated by Django 2.0.4 on 2018-11-30 20:37

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0078_development_lit_refs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='development',
            name='trial_url',
        ),
        migrations.AddField(
            model_name='development',
            name='estimated_completion',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='development',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Estimated trial completion date'),
        ),
        migrations.AlterField(
            model_name='development',
            name='lit_refs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.URLValidator()]), blank=True, default=list, size=None, verbose_name='Literature References'),
        ),
    ]
