# Generated by Django 2.0.4 on 2018-11-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0079_auto_20181130_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='development',
            old_name='estimated_completion',
            new_name='study_title',
        ),
    ]
