# Generated by Django 2.0.4 on 2018-12-03 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0081_remove_development_lit_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developments', to='compounds.Activity', verbose_name='Pharmacological activity'),
        ),
    ]
